const VERSION='1F-no-cache-20260705';
(async function killOldPwaCache(){try{if('serviceWorker' in navigator){const regs=await navigator.serviceWorker.getRegistrations(); await Promise.all(regs.map(r=>r.unregister()));} if('caches' in window){const keys=await caches.keys(); await Promise.all(keys.map(k=>caches.delete(k)));} console.log('HealthLens cache cleared', VERSION);}catch(e){console.warn('Cache cleanup skipped',e)}})();
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const layers=[['skin','Huid'],['organ','Organen'],['bone','Skelet'],['muscle','Spieren'],['vessel','Bloedvaten'],['nerve','Zenuwen'],['hormone','Hormonen']];
const content={
 head:{title:'Hoofd & hersenen',summary:'Hersenen, schedel, ogen, oren, sinussen, huid, kaak en belangrijke zenuwen.',details:['Alarmsignalen: plots scheve mond, krachtsverlies, spraakproblemen, verwardheid of ergste hoofdpijn ooit → spoed.','Veelvoorkomend: hoofdpijn, migraine, sinusklachten, kaakspanning, duizeligheid, huidproblemen.','Preventie: slaap, hydratatie, bloeddruk, zicht/gehoor, helm bij risico, stressmanagement.']},
 chest:{title:'Borstkas',summary:'Hart, longen, ribben, borstspieren, slokdarm en grote vaten.',details:['Alarmsignalen: druk op borst, uitstraling, benauwdheid, zweten, flauwvallen → spoed.','Mogelijke context: spier/ribklachten, reflux, luchtwegen, paniek, hart/long.','Preventie: niet roken, bewegen, bloeddruk, cholesterol, slaap en ademhaling.']},
 heart:{title:'Hart',summary:'Pompt bloed rond en reageert op belasting, stress, koorts, ritme en zuurstofbehoefte.',details:['Klachten kunnen verschillen per persoon; bij vrouwen/ouderen kunnen signalen vager zijn.','Let op: drukkende pijn, benauwdheid, zweten, misselijkheid, flauwvallen.','Gezond houden: bewegen, bloeddruk/cholesterol, slaap, stoppen met roken, behandel diabetes.']},
 lungs:{title:'Longen',summary:'Zuurstofopname, CO₂-afvoer en ademhaling.',details:['Alarmsignalen: blauwe lippen, ernstige benauwdheid, pijn bij ademhalen, bloed ophoesten.','Context: astma, infectie, hyperventilatie, allergie, longembolie.','Preventie: rookvrij, vaccinaties waar passend, conditie, luchtkwaliteit.']},
 abdomen:{title:'Buik',summary:'Lever, galblaas, maag, darmen, nieren, alvleesklier en bloedvaten.',details:['Let op: hevige buikpijn, harde buik, bloed bij ontlasting, aanhoudend braken, koorts.','Rechtsboven: lever/galblaas; rechtsonder: blindedarm/darmen; midden: maag/alvleesklier.','Preventie: vezels, vocht, beweging, alcohol beperken, gezonde voeding.']},
 liver:{title:'Lever & galblaas',summary:'Ontgifting, stofwisseling, galproductie, vet-/suikerhuishouding en medicatieverwerking.',details:['Klachten: rechterbovenbuik, geelzucht, donkere urine, jeuk, misselijkheid, vermoeidheid.','Alarmsignalen: geel oogwit, sufheid, bloedbraken, sterke buikzwelling → medische hulp.','Gezond houden: alcohol beperken, gezond gewicht, hepatitispreventie, medicatiebewust.']},
 gut:{title:'Maag & darmen',summary:'Spijsvertering, opname van voedingsstoffen, microbioom en afweer.',details:['Klachten: pijn, diarree, obstipatie, misselijkheid, reflux, bloed/slijm.','Alarmsignalen: bloed, zwarte ontlasting, gewichtsverlies, aanhoudende koorts, uitdroging.','Preventie: vezels, vocht, bewegen, gevarieerd eten, screening op leeftijd/familiegeschiedenis.']},
 kidney:{title:'Nieren & urinewegen',summary:'Filteren bloed, regelen vocht/zouten en maken urine.',details:['Klachten: flankpijn, pijn bij plassen, koorts, bloed in urine, vaak plassen.','Alarmsignalen: koorts + flankpijn, niet kunnen plassen, ernstige pijn, zwangerschap.','Preventie: hydratatie, bloeddruk, diabetescontrole, verstandig met pijnstillers.']},
 pelvis:{title:'Bekken & gevoelige regio',summary:'Blaas, voortplantingsorganen, bekkenbodem, huid en zenuwen.',details:['Onder 16: geen intieme foto’s/scans; klachten kunnen wél veilig met tekst worden beschreven.','Volwassenen: gevoelige klachten via privacy-first flow, geen automatische cloudopslag.','Onderwerpen: urine, menstruatie, seksuele gezondheid, puberteit, pijn, jeuk, afscheiding.']},
 arms:{title:'Armen, schouders & handen',summary:'Botten, spieren, pezen, zenuwen, bloedvaten en huid.',details:['Klachten: blessure, tinteling, krachtsverlies, gewrichtspijn, huid/wond.','Alarmsignalen: plots krachtsverlies, ernstige zwelling na trauma, koude/blauwe hand.','Preventie: ergonomie, kracht/mobiliteit, warming-up, wondzorg.']},
 legs:{title:'Benen, knieën & voeten',summary:'Heupen, knieën, enkels, spieren, bloedvaten, zenuwen en huid.',details:['Klachten: sportblessure, zwelling, pijn bij lopen, tinteling, wond, spataderen.','Alarmsignalen: één dik pijnlijk been, koude voet, niet kunnen belasten na trauma.','Preventie: kracht, balans, goede schoenen, beweging, valpreventie.']},
 thyroid:{title:'Schildklier',summary:'Regelt tempo van stofwisseling, energie, temperatuur en hartslag.',details:['Klachten kunnen vaag zijn: moe, koud/warm, hartkloppingen, gewicht, huid/haar, stemming.','Bespreek aanhoudende klachten met arts; bloedonderzoek kan relevant zijn.','Past binnen hormonen & levensfasen module.']},
 pancreas:{title:'Alvleesklier',summary:'Maakt spijsverteringsenzymen en hormonen zoals insuline.',details:['Let op hevige bovenbuikpijn naar rug, braken of geelzucht.','Preventie: gezond gewicht, alcohol beperken, diabetesrisico’s kennen.','Bij acute hevige pijn: medische hulp.']}
};
const knowledge=[
 ['Privacy-first','Gezondheidsdata, foto’s en profielen zijn gevoelig. HealthLens bewaart nu lokaal en wist oude PWA-cache automatisch.'],
 ['Kinderen & jongeren','Geen intieme beelden onder 16. Wel veilige symptoomvragen, puberteitsuitleg, SOA/STI-informatie en hulp bij onveiligheid.'],
 ['Hormonale context','Vage klachten kunnen samenhangen met levensfase, cyclus, schildklier, zwangerschap/postpartum of overgangsperiode.'],
 ['Erfelijkheid','Familiegeschiedenis kan relevant zijn bij hartziekten, kanker, stolling, stofwisseling en zeldzame aandoeningen.'],
 ['Huid & wond','Fotoanalyse vereist privacyfilter, belichting/kwaliteit, geen herkenbare achtergrond en duidelijke medische disclaimers.'],
 ['EHBO','Noodmodus moet offline beschikbaar worden: reanimatie, beroerte, verstikking, bloeding, brandwond en val.']
];
const flags=['druk op borst','benauwd','flauwvallen','scheve mond','krachtsverlies','spraakproblemen','hevige bloeding','koorts met sufheid','ernstige buikpijn','testikelpijn','zwangerschap','onveilig contact'];
function init(){renderLayers();renderFlags();renderKnowledge();bind();loadProfile();selectZone('chest');}
function renderLayers(){const box=$('#layerStrip'); box.innerHTML=''; layers.forEach(([id,label],i)=>{const b=document.createElement('button');b.className='layer-btn'+(i<2?' active':'');b.textContent=label;b.onclick=()=>toggleLayer(id,b);box.appendChild(b)});}
function toggleLayer(id,btn){const map={skin:'skinLayer',organ:'organLayer',bone:'boneLayer',muscle:'muscleLayer',vessel:'vesselLayer',nerve:'nerveLayer',hormone:'hormoneLayer'}; $('#'+map[id]).classList.toggle('on'); btn.classList.toggle('active');}
function renderFlags(){const box=$('#redFlags'); flags.forEach(f=>{const c=document.createElement('button');c.className='chip';c.textContent=f;c.onclick=()=>c.classList.toggle('active');box.appendChild(c)});}
function renderKnowledge(){const box=$('#knowledgeCards'); knowledge.forEach(([t,s])=>{const el=document.createElement('div');el.className='mini-card';el.innerHTML=`<b>${t}</b><small>${s}</small>`; box.appendChild(el)});}
function bind(){ $$('.zone').forEach(z=>z.addEventListener('click',e=>selectZone(e.currentTarget.dataset.zone))); $('#resetZoom').onclick=()=>{$('#bodyWrap').className='body-wrap'; selectZone('chest')}; $('#useForSymptoms').onclick=()=>{location.hash='symptoms'; $('#symptomText').value=`Klacht bij ${$('#infoTitle').textContent}: `; $('#symptomText').focus()}; $('#openProfile').onclick=()=>showProfile(); $('#skipProfile').onclick=()=>hideProfile(); $('#profileForm').onsubmit=e=>{e.preventDefault();saveProfile();hideProfile();}; $('#wipeProfile').onclick=()=>{localStorage.removeItem('healthlens.profile.1f');alert('Profiel gewist.');showProfile(true)}; $('#clearEverything').onclick=()=>{localStorage.clear();alert('Alle lokale HealthLens-data is gewist. Herlaad de pagina.');}; $('#analyzeBtn').onclick=analyze; }
function selectZone(zone){const c=content[zone]||content.chest; $('#infoTitle').textContent=c.title; $('#infoSummary').textContent=c.summary; $('#infoDetails').innerHTML=c.details.map(d=>`<div class="detail">${d}</div>`).join(''); $('#bodyWrap').className='body-wrap zoom-'+zone;}
function showProfile(force=false){$('#profileGate').classList.remove('hidden'); if(force){$('#age').value='';$('#sex').value='prefer-not';$('#background').value='prefer-not';}}
function hideProfile(){$('#profileGate').classList.add('hidden')}
function saveProfile(){const p={age:$('#age').value,sex:$('#sex').value,background:$('#background').value,language:$('#language').value,updated:new Date().toISOString()};localStorage.setItem('healthlens.profile.1f',JSON.stringify(p));}
function loadProfile(){try{const p=JSON.parse(localStorage.getItem('healthlens.profile.1f')||'null'); if(!p){showProfile(); return;} $('#age').value=p.age||''; $('#sex').value=p.sex||'prefer-not'; $('#background').value=p.background||'prefer-not'; $('#language').value=p.language||'nl';}catch{showProfile();}}
function analyze(){const text=$('#symptomText').value.trim(); const active=$$('#redFlags .active').map(x=>x.textContent); const p=JSON.parse(localStorage.getItem('healthlens.profile.1f')||'{}'); let level='Zelfzorg / observeer'; let tone=''; if(active.length){level='Neem contact op met medische hulp; bij ernstige of plotselinge klachten spoed.'; tone='warn'} if(active.some(x=>['druk op borst','benauwd','flauwvallen','scheve mond','krachtsverlies','spraakproblemen','hevige bloeding'].includes(x))){level='Spoedadvies: bel lokale spoedhulp bij acute of ernstige klachten.'; tone='danger'} const age=Number(p.age||0); const notes=[]; if(age && age<16) notes.push('Onder 16: geen intieme foto/scans; beschrijf gevoelige klachten veilig met tekst en betrek een vertrouwde volwassene/arts waar nodig.'); if(p.sex==='female' && age>=38 && age<=55) notes.push('Bij vage, wisselende klachten kan hormonale levensfasecontext relevant zijn, zonder andere oorzaken uit te sluiten.'); if(p.background && p.background!=='prefer-not') notes.push('Achtergrond wordt alleen gebruikt als context voor verschillen in presentatie, huidbeeld of risico; niet als harde diagnosefactor.'); $('#result').innerHTML=`<h3 class="${tone}">${level}</h3><p>${text?`Samenvatting: ${text}`:'Voeg klachttekst toe voor betere context.'}</p><p>Geselecteerde alarmsignalen: ${active.length?active.join(', '):'geen'}</p>${notes.map(n=>`<div class="detail">${n}</div>`).join('')}<p class="muted">Indicatief. Geen definitieve diagnose. Bij twijfel, verslechtering of alarmsignalen: professionele hulp.</p>`;}
document.addEventListener('DOMContentLoaded',init);
