
window.MEDDB = {
  hart:{
    naam:"Hart", systeem:"Hart en vaten",
    omschrijving:"Het hart is een spierpomp met vier kamers die bloed door het lichaam rondstuurt.",
    functie:"Zuurstofrijk bloed rondpompen naar alle weefsels en organen; afvoeren van CO₂.",
    klachten:["Pijn of druk op de borst","Kortademigheid","Hartkloppingen","Duizeligheid","Verminderd inspanningsvermogen","Vermoeidheid"],
    rodeVlaggen:["Drukkende borstpijn met uitstraling naar arm, kaak of rug","Koud zweet met misselijkheid","Ernstige benauwdheid","Flauwvallen","Pijn die niet zakt in rust","Onregelmatige polsslag met wegraken"],
    preventie:["Niet roken","Regelmatig bewegen","Gezond eten met minder verzadigd vet","Bloeddruk laten controleren","Cholesterol en glucose in de gaten houden","Gezond gewicht","Stress en slaap"],
    eersteHulp:["Bel 112 bij verdenking hartinfarct","Laat de persoon rustig zitten","Knellende kleding losmaken","Zo nodig reanimatie starten"],
    differentiaal:["Hartinfarct","Angina pectoris","Ritmestoornis","Pericarditis","Refluxklachten","Borstwandpijn"],
    leren:"Het hart pompt ongeveer 5 liter bloed per minuut in rust en veel meer bij inspanning. Coronaire vaten voorzien de hartspier zelf van zuurstof.",
    follow_up:["Wanneer treedt de klacht op?","Straalt de pijn uit?","Neemt de klacht toe bij inspanning?","Is er zweten of misselijkheid?"]
  },
  longen:{
    naam:"Longen", systeem:"Ademhaling",
    omschrijving:"De longen zorgen voor gasuitwisseling tussen ingeademde lucht en het bloed.",
    functie:"Opname van zuurstof en afgifte van koolstofdioxide.",
    klachten:["Hoesten","Kortademigheid","Piepende ademhaling","Slijm ophoesten","Pijn bij ademen","Verminderd uithoudingsvermogen"],
    rodeVlaggen:["Bloed ophoesten","Ernstige benauwdheid in rust","Blauwe lippen of vingers","Plotselinge scherpe borstpijn","Hoge koorts met benauwdheid","Niet meer kunnen praten door kortademigheid"],
    preventie:["Niet roken","Vermijd luchtvervuiling en fijnstof","Beweging en cardio-training","Vaccinaties (griep, pneumokokken)","Allergenen vermijden","Adequate behandeling van astma/COPD"],
    eersteHulp:["Bij ernstige benauwdheid: 112","Rechtop laten zitten","Rustig proberen ademen","Bekende inhalatie-medicatie gebruiken"],
    differentiaal:["Astma","COPD","Longontsteking","Longembolie","Bronchitis","Pneumothorax"],
    leren:"Volwassenen ademen ongeveer 12–20 keer per minuut. Elke long bevat honderden miljoenen longblaasjes voor gasuitwisseling.",
    follow_up:["Sinds wanneer bestaat de kortademigheid?","Ligt u ’s nachts hoger in bed?","Heeft u koorts?","Zijn er reisdagen of immobilisatie geweest?"]
  },
  hersenen:{
    naam:"Hersenen", systeem:"Zenuwstelsel",
    omschrijving:"Centraal orgaan van het zenuwstelsel dat denken, waarneming, beweging en autonome functies regelt.",
    functie:"Verwerken van informatie, aansturing van spieren en regulatie van bewustzijn en emoties.",
    klachten:["Hoofdpijn","Duizeligheid","Concentratieproblemen","Slaapproblemen","Tintelingen","Vermoeidheid"],
    rodeVlaggen:["Plotselinge zeer hevige hoofdpijn","Verlamming aan één zijde","Spraakproblemen","Bewustzijnsverlies","Nieuwe epileptische aanval","Verwardheid met koorts"],
    preventie:["Voldoende slaap","Bewegen","Gezonde bloeddruk","Beperk alcohol","Sociale en cognitieve activiteit","Helm bij fietsen/skiën"],
    eersteHulp:["FAST-test bij verdenking beroerte en 112","Bij aanval: hoofd beschermen, niets in mond","Bij bewustzijnsverlies: stabiele zijligging"],
    differentiaal:["Spanningshoofdpijn","Migraine","Beroerte (TIA/CVA)","Hersenschudding","Meningitis","Hersentumor"],
    leren:"De hersenen wegen ongeveer 1,3–1,4 kg en bevatten 86 miljard neuronen. Bloedstroom is essentieel: enkele minuten zonder zuurstof geeft blijvende schade.",
    follow_up:["Wanneer begon de hoofdpijn?","Is dit uw ergste hoofdpijn ooit?","Zijn er bijkomende neurologische verschijnselen?","Neemt u bloedverdunners?"]
  },
  ruggenmerg:{
    naam:"Ruggenmerg", systeem:"Zenuwstelsel",
    omschrijving:"Het ruggenmerg loopt door de wervelkolom en verbindt de hersenen met perifere zenuwen.",
    functie:"Geleiding van motorische en sensorische signalen; reflexen.",
    klachten:["Rugpijn","Uitstralende pijn in been of arm","Tintelingen","Krachtsverlies","Loopstoornis"],
    rodeVlaggen:["Verlies van blaas- of darmcontrole","Zadelanesthesie","Progressieve krachtsvermindering","Ernstige pijn na trauma","Koorts met rugpijn"],
    preventie:["Sterke rugspieren","Tilinstructies","Ergonomische werkplek","Vermijd langdurig stilzitten"],
    eersteHulp:["Bij verdenking wervelletsel: niet bewegen, 112","Neurologische symptomen: spoedbeoordeling"],
    differentiaal:["Hernia","Spinale stenose","Cauda equina","Ruggenmergletsel","Ontsteking"],
    leren:"Het ruggenmerg eindigt meestal ter hoogte van L1–L2 als de cauda equina, een bundel zenuwwortels.",
    follow_up:["Zijn er problemen met plassen of ontlasting?","Is er gevoelloosheid rond het zitvlak?","Is er sprake van een trauma?"]
  },
  lever:{
    naam:"Lever", systeem:"Spijsvertering",
    omschrijving:"Grootste inwendige orgaan; centraal in stofwisseling en ontgifting.",
    functie:"Ontgifting, eiwit- en galproductie, energieopslag, immuunfuncties.",
    klachten:["Vermoeidheid","Gele huid of ogen (geelzucht)","Pijn rechtsboven","Misselijkheid","Jeuk","Donkere urine"],
    rodeVlaggen:["Geelzucht met verwardheid","Bloedbraken","Zwarte ontlasting","Ernstige rechterbovenbuikpijn met koorts"],
    preventie:["Beperk alcohol","Gezond gewicht","Voorzichtig met paracetamol en NSAID's","Vaccinatie hepatitis A/B","Veilige seks en steriele naalden"],
    eersteHulp:["Bij bloedbraken of zwarte ontlasting: 112","Bij verwardheid en geelzucht: spoedbeoordeling"],
    differentiaal:["Virale hepatitis","Leversteatose","Alcoholische leverziekte","Levercirrose","Galwegobstructie"],
    leren:"De lever kan zich sterk regenereren, maar chronische schade leidt tot fibrose en cirrose.",
    follow_up:["Hoeveel alcohol drinkt u per week?","Neemt u receptvrije pijnstillers?","Zijn de ogen geel?"]
  },
  galblaas:{
    naam:"Galblaas", systeem:"Spijsvertering",
    omschrijving:"Peervormig reservoir onder de lever dat gal opslaat.",
    functie:"Opslag en concentratie van gal, afgifte aan de darm bij vetrijke maaltijden.",
    klachten:["Pijn rechtsboven","Krampen na vet eten","Misselijkheid","Opgeblazen gevoel"],
    rodeVlaggen:["Hoge koorts met rillen","Geelzucht","Aanhoudende hevige buikpijn","Ernstige buikpijn met braken"],
    preventie:["Gezond gewicht","Vezelrijk eten","Vermijd snelle gewichtsschommelingen"],
    eersteHulp:["Bij aanhoudende ernstige pijn of koorts: huisartsenpost/SEH"],
    differentiaal:["Galstenen","Cholecystitis","Choledocholithiasis","Galwegobstructie"],
    leren:"Galstenen komen vaker voor bij vrouwen, oudere leeftijd en overgewicht.",
    follow_up:["Komt de pijn na vet eten?","Straalt de pijn uit naar de schouder?"]
  },
  alvleesklier:{
    naam:"Alvleesklier", systeem:"Spijsvertering / Endocrien",
    omschrijving:"Klier achter de maag met exocriene en endocriene functies.",
    functie:"Productie van verteringsenzymen en hormonen (insuline en glucagon).",
    klachten:["Bovenbuikpijn","Misselijkheid","Vettige ontlasting","Gewichtsverlies"],
    rodeVlaggen:["Hevige aanhoudende bovenbuikpijn uitstralend naar de rug","Braken met koorts","Geelzucht met gewichtsverlies","Aanhoudende buikpijn met shock"],
    preventie:["Beperk alcohol","Niet roken","Gezond gewicht","Behandeling van hoge triglyceriden"],
    eersteHulp:["Bij verdenking pancreatitis: spoedbeoordeling"],
    differentiaal:["Acute pancreatitis","Chronische pancreatitis","Alvleesklierkanker"],
    leren:"Insuline uit de bètacellen regelt de bloedsuiker; tekort veroorzaakt diabetes.",
    follow_up:["Drinkt u alcohol?","Is er sprake van galstenen?"]
  },
  maag:{
    naam:"Maag", systeem:"Spijsvertering",
    omschrijving:"Zakvormig orgaan dat voedsel opslaat en met maagzuur voorverteert.",
    functie:"Voorvertering en gecontroleerde afgifte aan de dunne darm.",
    klachten:["Bovenbuikpijn","Zuurbranden","Misselijkheid","Braken","Vol gevoel","Boeren"],
    rodeVlaggen:["Bloedbraken","Zwarte ontlasting","Onverklaard gewichtsverlies","Slikklachten"],
    preventie:["Vermijd overmatig alcohol","Beperk NSAID's","Regelmatige maaltijden","Stop roken"],
    eersteHulp:["Bij bloedbraken 112","Bij ernstige pijn: huisartsenpost"],
    differentiaal:["Refluxziekte","Gastritis","Maagzweer","H. pylori-infectie","Maagcarcinoom"],
    leren:"De maag maakt zoutzuur en pepsine om eiwitten af te breken en bacteriën te doden.",
    follow_up:["Neemt u regelmatig ontstekingsremmers?","Wordt u ’s nachts wakker van pijn?"]
  },
  dunne_darm:{
    naam:"Dunne darm", systeem:"Spijsvertering",
    omschrijving:"Ongeveer 6 meter lang; belangrijkste plaats van voedselopname.",
    functie:"Vertering en absorptie van voedingsstoffen.",
    klachten:["Krampen","Diarree","Opgeblazen gevoel","Gewichtsverlies","Vermoeidheid"],
    rodeVlaggen:["Hevige aanhoudende pijn","Braken met koorts","Bloed bij ontlasting","Sterke dehydratie","Zwarte ontlasting"],
    preventie:["Vezels en variatie","Voldoende drinken","Hygiëne bij eten","Vaccinaties op reis"],
    eersteHulp:["Bij dehydratie: ORS","Bij ileus-verdenking: SEH"],
    differentiaal:["Coeliakie","Ziekte van Crohn","Voedselovergevoeligheid","Infectieuze enteritis","Ileus"],
    leren:"De darmvlokken vergroten het absorberend oppervlak enorm.",
    follow_up:["Zijn er triggers zoals melk of gluten?","Bent u recent op reis geweest?"]
  },
  dikke_darm:{
    naam:"Dikke darm", systeem:"Spijsvertering",
    omschrijving:"Absorbeert water en zouten en vormt ontlasting.",
    functie:"Wateropname, opslag en afvoer van ontlasting.",
    klachten:["Buikpijn","Obstipatie","Diarree","Slijm of bloed bij ontlasting","Opgeblazen gevoel"],
    rodeVlaggen:["Bloed bij ontlasting","Onverklaard gewichtsverlies","Nachtelijke diarree","Verandering ontlastingspatroon >6 wk","Familiaire darmkanker"],
    preventie:["Vezelrijk eten","Voldoende drinken","Beweging","Screening vanaf 55 jaar"],
    eersteHulp:["Bij hevige buikpijn met koorts: huisartsenpost"],
    differentiaal:["Prikkelbare darm","Diverticulitis","IBD","Coloncarcinoom","Aambeien"],
    leren:"Het microbioom in de dikke darm speelt een rol in de immuunfunctie.",
    follow_up:["Ziet u bloed of slijm?","Wisselt uw stoelgangpatroon?"]
  },
  nieren:{
    naam:"Nieren", systeem:"Urinewegen",
    omschrijving:"Twee boonvormige organen die bloed filteren en urine maken.",
    functie:"Filtratie, elektrolytenbalans, bloeddrukregulatie, hormoonproductie.",
    klachten:["Flankpijn","Bloed in urine","Vaak plassen","Vermoeidheid","Vochtophoping"],
    rodeVlaggen:["Weinig of geen urine","Hoge koorts met flankpijn","Zichtbaar bloed in urine","Ernstige rugpijn met braken"],
    preventie:["Voldoende drinken","Bloeddruk en glucose onder controle","Beperk zout","Voorzichtig met NSAID's"],
    eersteHulp:["Bij koorts met flankpijn: contact huisartsenpost","Bij anurie: SEH"],
    differentiaal:["Nierstenen","Urineweginfectie","Pyelonefritis","Nierinsufficiëntie","Glomerulonefritis"],
    leren:"De nieren filteren dagelijks ongeveer 180 liter bloed en produceren zo'n 1,5 liter urine.",
    follow_up:["Straalt de pijn uit naar de lies?","Is de urine roze of bruin?"]
  },
  blaas:{
    naam:"Blaas", systeem:"Urinewegen",
    omschrijving:"Elastisch reservoir dat urine opslaat tot aan het plassen.",
    functie:"Opslag en gecontroleerde uitscheiding van urine.",
    klachten:["Vaak plassen","Pijn bij plassen","Sterke aandrang","Onvrijwillig urineverlies","Bloed in urine"],
    rodeVlaggen:["Koorts met flankpijn","Niet kunnen plassen","Zichtbaar bloed in urine","Verwardheid bij ouderen met UWI-symptomen"],
    preventie:["Voldoende drinken","Goede hygiëne","Niet te lang ophouden","Bekkenbodemtraining"],
    eersteHulp:["Bij niet kunnen plassen: SEH"],
    differentiaal:["Blaasontsteking","Prostaatvergroting","Blaassteen","Blaascarcinoom","Overactieve blaas"],
    leren:"De normale blaascapaciteit is ongeveer 400–600 ml.",
    follow_up:["Is er koorts?","Is er bloed te zien?"]
  },
  milt:{
    naam:"Milt", systeem:"Lymfestelsel",
    omschrijving:"Filtert bloed en speelt rol in het afweersysteem.",
    functie:"Afbraak van oude rode bloedcellen, antistofproductie, opslag bloedcellen.",
    klachten:["Pijn linksboven","Vermoeidheid","Vergrote buik"],
    rodeVlaggen:["Ernstige buikpijn na trauma","Snel toenemende buikzwelling met bleekheid","Shock na buiktrauma"],
    preventie:["Voorkom buiktrauma","Vaccinaties na miltverwijdering"],
    eersteHulp:["Bij verdenking miltruptuur: 112"],
    differentiaal:["Miltruptuur","Mononucleosis","Lymfoom","Splenomegalie bij bloedziekten"],
    leren:"Bij afwezigheid van de milt is er extra risico op infecties door bepaalde bacteriën.",
    follow_up:["Recent contactsport of val?","Recent Pfeiffer of virale ziekte?"]
  },
  schildklier:{
    naam:"Schildklier", systeem:"Endocrien",
    omschrijving:"Vlinder-vormige klier voor in de hals die schildklierhormoon maakt.",
    functie:"Regulatie van stofwisseling, hartslag, temperatuur.",
    klachten:["Vermoeidheid","Gewichtsverandering","Koude of warmte-intolerantie","Haaruitval","Hartkloppingen"],
    rodeVlaggen:["Snelgroeiende halszwelling","Slikklachten of heesheid","Ernstige hartkloppingen met koorts"],
    preventie:["Voldoende jodium","Bekende schildklierproblemen laten monitoren"],
    eersteHulp:["Bij thyreotoxische crisis: SEH"],
    differentiaal:["Hypothyreoïdie","Hyperthyreoïdie","Struma","Schildklierknobbel"],
    leren:"Schildklieraandoeningen zijn frequent, vooral bij vrouwen.",
    follow_up:["Bent u afgevallen zonder reden?","Is er zwelling in de hals?"]
  },
  bijnier:{
    naam:"Bijnieren", systeem:"Endocrien",
    omschrijving:"Kleine klieren op de nieren die cortisol, adrenaline en aldosteron maken.",
    functie:"Regulatie van stress, bloeddruk en zoutbalans.",
    klachten:["Vermoeidheid","Duizeligheid bij opstaan","Gewichtsverlies","Hoge bloeddruk","Buikpijn"],
    rodeVlaggen:["Extreme uitputting met lage bloeddruk","Braken met dehydratie","Verwardheid met bekende bijnierziekte"],
    preventie:["Bij bekende ziekte: stressdosering steroïden","Bloeddruk monitoren"],
    eersteHulp:["Bij Addison-crisis: 112 en hydrocortison zoals afgesproken"],
    differentiaal:["Ziekte van Addison","Syndroom van Cushing","Feochromocytoom"],
    leren:"Cortisol volgt een dagritme met piek in de ochtend.",
    follow_up:["Duizelig bij opstaan?","Onverklaarde hoge bloeddruk?"]
  },
  huid:{
    naam:"Huid", systeem:"Huid",
    omschrijving:"Grootste orgaan; barrière, temperatuurregulatie en zintuig.",
    functie:"Bescherming, waarneming, temperatuurregulatie, vitamine-D productie.",
    klachten:["Jeuk","Uitslag","Droge huid","Veranderde moedervlek","Wond die niet geneest"],
    rodeVlaggen:["Snel groeiende moedervlek","Uitslag met hoge koorts en niet-weg-drukbare vlekjes","Grote brandwonden","Wond met ernstige zwelling en koorts"],
    preventie:["Bescherming tegen zon","Vermijd tabaksrook","Hydratatie","Regelmatige zelfinspectie"],
    eersteHulp:["Brandwond: 10 min lauw water; groot >SEH","Meningokokkenverdenking: 112"],
    differentiaal:["Eczeem","Psoriasis","Melanoom","Basaalcelcarcinoom","Cellulitis"],
    leren:"ABCDE-regel helpt bij het beoordelen van moedervlekken (Asymmetrie, Border, Color, Diameter, Evolution).",
    follow_up:["Is de moedervlek veranderd?","Zijn er nachtzweten of gewichtsverlies?"]
  },
  oog:{
    naam:"Oog", systeem:"Zintuigen",
    omschrijving:"Complex zintuig dat licht omzet in visuele informatie.",
    functie:"Beeldvorming en scherpstelling.",
    klachten:["Wazig zien","Roodheid","Pijn","Lichtflitsen","Vlekjes (floaters)","Droge ogen"],
    rodeVlaggen:["Plotseling gezichtsverlies","Ernstige oogpijn met braken","Chemisch letsel","Trauma","Gordijn voor het oog"],
    preventie:["UV-bescherming","Pauzes bij schermwerk","Rookstop","Regelmatige oogcontrole bij risico"],
    eersteHulp:["Chemisch letsel: 15 min spoelen met water, dan SEH","Plots verlies zicht: SEH"],
    differentiaal:["Conjunctivitis","Glaucoom","Netvliesloslating","Uveïtis","Migraine met aura"],
    leren:"Bij 40+ ontstaat vaak leesbrilbehoefte door presbyopie.",
    follow_up:["Is het gezichtsverlies plots?","Is er trauma geweest?"]
  },
  oor:{
    naam:"Oor", systeem:"Zintuigen",
    omschrijving:"Bevat gehoor- en evenwichtsorgaan.",
    functie:"Horen en evenwicht.",
    klachten:["Oorpijn","Slechthorendheid","Oorsuizen","Duizeligheid","Loopoor"],
    rodeVlaggen:["Plots gehoorverlies","Ernstige oorpijn met koorts","Aangezichtsuitval","Ernstige duizeligheid met braken"],
    preventie:["Gehoorbescherming","Vermijd wattenstaafjes diep in de gehoorgang","Vaccinaties"],
    eersteHulp:["Bij aangezichtsuitval: SEH","Bij plots gehoorverlies: dezelfde dag KNO"],
    differentiaal:["Otitis media","Otitis externa","Cerumen","Ziekte van Ménière","Vestibulaire neuritis"],
    leren:"Het evenwichtsorgaan zit in het binnenoor en werkt samen met ogen en gewrichten.",
    follow_up:["Is er koorts?","Hoort u minder aan één zijde?"]
  },
  spieren:{
    naam:"Spieren", systeem:"Bewegingsapparaat",
    omschrijving:"Spieren zetten prikkels om in beweging.",
    functie:"Beweging, houding, warmteproductie.",
    klachten:["Spierpijn","Kramp","Zwakte","Stijfheid","Zwelling","Beperkte functie"],
    rodeVlaggen:["Ernstige zwakte","Donkere urine na extreme belasting","Zwelling met ernstige pijn","Niet kunnen gebruiken na trauma"],
    preventie:["Geleidelijke opbouw","Warming-up","Voldoende eiwit","Hydratatie","Herstel"],
    eersteHulp:["RICE (rust, ijs, compressie, hoog)","Bij verdenking scheur: beoordeling"],
    differentiaal:["Spierverrekking","Peesontsteking","Rabdomyolyse","Compartimentsyndroom"],
    leren:"Herstel na krachttraining verloopt via micro-scheurtjes die zich adaptief herstellen.",
    follow_up:["Is er een trauma geweest?","Is de urine donker?"]
  },
  skelet:{
    naam:"Skelet", systeem:"Bewegingsapparaat",
    omschrijving:"Ongeveer 206 botten die het lichaam ondersteunen en organen beschermen.",
    functie:"Steun, bescherming, hefboom voor beweging, mineraalopslag.",
    klachten:["Pijn","Zwelling","Bewegingsbeperking","Vervorming","Krakend geluid"],
    rodeVlaggen:["Vervorming","Niet kunnen belasten","Gevoelloos of koud ledemaat na letsel","Koorts met botpijn"],
    preventie:["Krachttraining","Calcium en vitamine D","Niet roken","Valpreventie","Botdichtheidsmeting bij risico"],
    eersteHulp:["Immobiliseren bij verdenking breuk","Bij open fractuur of doorbloedingsstoornis: 112"],
    differentiaal:["Fractuur","Osteoporose","Osteoartritis","Botinfectie","Bottumor"],
    leren:"Bot wordt levenslang afgebroken en opgebouwd; piekbotmassa rond 25e levensjaar.",
    follow_up:["Kunt u het lichaamsdeel gebruiken?","Is er een val geweest?"]
  },
  ribbenkast:{
    naam:"Ribbenkast", systeem:"Bewegingsapparaat / Ademhaling",
    omschrijving:"12 paar ribben die hart en longen beschermen en meebewegen bij ademhaling.",
    functie:"Bescherming van thoraxorganen en ondersteuning ademhaling.",
    klachten:["Borstwandpijn bij bewegen","Pijn bij drukken","Pijn bij diep ademen"],
    rodeVlaggen:["Ernstige benauwdheid na trauma","Instabiele borstwand","Bloed ophoesten"],
    preventie:["Voorkom vallen","Voorzichtig bij contactsport"],
    eersteHulp:["Bij hevige benauwdheid of borstpijn: 112","Bij ribcontusie: pijnstilling en ademhalingsoefeningen"],
    differentiaal:["Ribfractuur","Costochondritis","Pneumothorax","Longcontusie"],
    leren:"Bij ribfracturen is pijnstilling belangrijk om longontsteking te voorkomen.",
    follow_up:["Is er een trauma geweest?","Is er kortademigheid?"]
  },
  wervelkolom:{
    naam:"Wervelkolom", systeem:"Bewegingsapparaat / Zenuwstelsel",
    omschrijving:"33 wervels met tussenwervelschijven die romp en hoofd dragen.",
    functie:"Steun, beweging, bescherming van het ruggenmerg.",
    klachten:["Rugpijn","Nekpijn","Uitstralende pijn","Stijfheid","Tintelingen"],
    rodeVlaggen:["Progressieve krachtsvermindering","Zadelanesthesie","Verlies blaas/darmcontrole","Rugpijn met koorts","Onverklaard gewichtsverlies met rugpijn"],
    preventie:["Rug- en core-training","Ergonomie","Regelmatig bewegen","Gezond gewicht","Tilinstructies"],
    eersteHulp:["Bij trauma en neurologische uitval: 112","Blijf zoveel mogelijk bewegen bij aspecifieke rugpijn"],
    differentiaal:["Aspecifieke lage rugpijn","Hernia","Spinale stenose","Osteoporose-fractuur","Spondylitis"],
    leren:"De meeste rugpijn geneest binnen 6 weken zonder specifieke oorzaak.",
    follow_up:["Straalt de pijn uit onder de knie?","Zijn er blaas- of darmklachten?"]
  },
  bekken:{
    naam:"Bekken", systeem:"Bewegingsapparaat",
    omschrijving:"Beenring die romp met benen verbindt en organen ondersteunt.",
    functie:"Steun, kracht-overdracht en bescherming van bekkenorganen.",
    klachten:["Pijn in de lies","Pijn aan bekkenrand","Instabiel gevoel","Loopstoornis"],
    rodeVlaggen:["Ernstige pijn na hoog-energetisch trauma","Niet kunnen staan","Bloedverlies uit urinewegen na trauma"],
    preventie:["Krachttraining","Valpreventie","Zwangerschapszorg bij bekkenpijn"],
    eersteHulp:["Bij hoog-energetisch trauma: 112 en immobiliseren"],
    differentiaal:["Bekkenfractuur","Bekkeninstabiliteit","Bursitis","Heup-artrose"],
    leren:"Bekkenfracturen bij ouderen kunnen ook na een simpele val ontstaan.",
    follow_up:["Was er een val?","Kunt u belasten?"]
  },
  knie:{
    naam:"Knie", systeem:"Bewegingsapparaat",
    omschrijving:"Groot en complex scharniergewricht.",
    functie:"Buigen, strekken en licht draaien; belasting dragen tijdens lopen.",
    klachten:["Pijn","Zwelling","Instabiliteit","Knakken of blokkeren","Startpijn"],
    rodeVlaggen:["Niet kunnen belasten na trauma","Duidelijke vervorming","Grote zwelling met koorts"],
    preventie:["Sterke bovenbeenspieren","Gezond gewicht","Goede schoeisel","Techniek bij sport"],
    eersteHulp:["RICE bij milde blessure","Bij verdenking fractuur of ligamentletsel: beoordeling"],
    differentiaal:["Meniscusletsel","Kruisbandletsel","Artrose","Patella-tendinopathie","Bursitis"],
    leren:"De voorste kruisband is een frequent letsel bij draaisporten.",
    follow_up:["Ging er iets ‘pop’ tijdens het letsel?","Is de knie warm en rood?"]
  },
  schouder:{
    naam:"Schouder", systeem:"Bewegingsapparaat",
    omschrijving:"Meest beweeglijke gewricht van het lichaam.",
    functie:"Grote bewegingsuitslag van de arm; combinatie van meerdere gewrichten.",
    klachten:["Pijn","Bewegingsbeperking","Nachtelijke pijn","Krachtsverlies","Instabiliteit"],
    rodeVlaggen:["Duidelijke vervorming na trauma","Uitstralende pijn met tintelingen tot hand","Krachtsverlies na trauma"],
    preventie:["Sterke rotator cuff","Techniek bij bovenhandse sporten","Ergonomie"],
    eersteHulp:["Bij verdenking luxatie: niet zelf reponeren, immobiliseren","Bij fractuur: beoordeling"],
    differentiaal:["Rotator cuff-tendinopathie","Impingement","Frozen shoulder","Artrose","Luxatie"],
    leren:"De schouder wordt vooral door spieren en pezen stabiel gehouden, niet door bot.",
    follow_up:["Kunt u de arm heffen?","Was er trauma?"]
  }
};
